### ISSUE TITLE
Move vi code from kitura-ubuntu dockerfile to this repo.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-ubuntu-docker#10]

**Comment by dsperling** [comment]
@rolivieri I had removed the vim package during this reflector for Dockerfile best practices:
https://github.com/IBM-Swift/swift-ubuntu-docker/commit/832dde1fd540bba3f8e80c5b794130af9511682c

I did so to match the published Dockerfile best practices that says:

> Avoid installing unnecessary packages
> In order to reduce complexity, dependencies, file sizes, and build times, you should avoid installing extra or unnecessary packages just because they might be “nice to have.” For example, you don’t need to include a text editor in a database image.

However, in the end, this image needs to be usable by the team.  Since this image is used to not only deploy swift apps, but to also test and debug, **vi is a critical component**.

**Comment by rolivieri** [comment]
@dsperling No worries, I remember that was one of the changes in the PR. I did not have a need for it either but it turned out that other team members have a need for vi as a critical component in this docker image.

**Comment by BDHernand** [comment]
this has been commited to master.  Closing
